### ISSUE TITLE
Hackage docs

### ISSUE THREAD

**Issue by georgefst** [LeifW/udev#4]
Version `0.1.1.0` doesn't have any docs on Hackage.

This can be fixed by running `cabal haddock --haddock-for-hackage`, and passing the resulting tarball to `cabal upload --publish --doc`.

**Comment by LeifW** [comment]
Done, thanks!
Up at http://hackage.haskell.org/package/udev
Don't know why they failed to build on there.

**Comment by georgefst** [comment]
Yeah, I've never been sure what determines whether they manage to build, so I just always upload manually.
